[package]
name = "azalea-viaversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
azalea = { git = "https://github.com/azalea-rs/azalea", default-features = false }
futures-util = "0.3.30"
indicatif = "0.17.8"
portpicker = "0.1.1"
regex = "1.10.4"
reqwest = { version = "0.12.4", default-features = false, features = [
    "rustls-tls",
    "stream",
] }
tokio = { version = "1.37.0", features = ["process"] }
tracing = "0.1.40"
